volumes:
  static_root:

services:
  web: # Name of this container should not be changed
    image: ogcapi
    restart: unless-stopped
    command: "gunicorn geocity.wsgi -b :9000 --error-logfile gunicorn_log.log --workers=2 --threads=4 --worker-class=gthread"
    environment:
      ENV: PROD
      PGDATABASE:
      PGUSER:
      PGPASSWORD:
      PGHOST:
      PGPORT:
      SECRET_KEY:
    ports:
      - "${DJANGO_DOCKER_PORT}:9000"
    entrypoint: /code/entrypoint.sh

