# Overrides for development
volumes:
  pgdata:

services:
  web:
    image: ogapi
    build:
      args:
        ENV: DEV

    # Uncomment those two lines for debug
    #tty: true
    #stdin_open: true
    environment:
      ENV: DEV
    # Runserver for live reload
    command: "python3 manage.py runserver 0.0.0.0:9000"
    volumes:
      # Mount code for live reload
      - .:/code
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${DJANGO_DOCKER_PORT}:9000"

  postgres:
    image: postgis/postgis:16-3.5
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "${PGUSER}", "-d", "${PGDATABASE}" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - "${POSTGRES_DOCKER_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

